application: mrkcttn
version: crm-10
runtime: python
api_version: 1


builtins:
- datastore_admin: on

handlers:
- url: /_ah/mail/.+ 
  script: main.py
  
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /img
  static_dir: img
  
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
  
- url: /robots.txt
  static_files: img/robots.txt
  upload: img/robots.txt

- url: .*
  script: main.py

